-- 添加数据库脚本时，以'-- ' + 当前日期(数据库的脚本注释格式)为开头，下面跟数据库脚本。脚本中不可以加额外字符，以方便运维人员直接复制。


-- 2017-07-26
ALTER TABLE `pdcre`.`tra_resource`     ADD COLUMN `DETAILOPERATION` VARCHAR(2000) NULL AFTER `DESCRIPTION`;

-- 2017-07-05
CREATE TABLE UPM_USERDEPARTMENTROLE (
          ID           VARCHAR(36) NOT NULL,
          ROLEID         VARCHAR(36) NOT NULL,
          USERID VARCHAR(36) NOT NULL
    );
CREATE TABLE UPM_DEPARTMENTROLEPRIVILEGE (
	  ID           VARCHAR(36) NOT NULL,
	  ROLEID         VARCHAR(36) NOT NULL,
	  DEPARTMENTID VARCHAR(36) NOT NULL,
	  PRIVILEGEID  VARCHAR(64) NOT NULL,
	  STATUS DECIMAL
);
CREATE TABLE UPM_DEPARTMENTROLE (
	  ID           VARCHAR(36) NOT NULL,
	  NAME         VARCHAR(36) NOT NULL,
	  DEPARTMENTID VARCHAR(36) NOT NULL,
	  DESCRIPTION  VARCHAR(64)
);