-- 2017-07-26
ALTER TABLE `pdcre`.`tra_resource`     ADD COLUMN `DETAILOPERATION` VARCHAR(2000) NULL AFTER `DESCRIPTION`;

-- 2017-07-05
CREATE TABLE UPM_USERDEPARTMENTROLE (
          ID           VARCHAR(36) NOT NULL,
          ROLEID         VARCHAR(36) NOT NULL,
          USERID VARCHAR(36) NOT NULL
    );
CREATE TABLE UPM_DEPARTMENTROLEPRIVILEGE (
	  ID           VARCHAR(36) NOT NULL,
	  ROLEID         VARCHAR(36) NOT NULL,
	  DEPARTMENTID VARCHAR(36) NOT NULL,
	  PRIVILEGEID  VARCHAR(64) NOT NULL,
	  STATUS DECIMAL
);
CREATE TABLE UPM_DEPARTMENTROLE (
	  ID           VARCHAR(36) NOT NULL,
	  NAME         VARCHAR(36) NOT NULL,
	  DEPARTMENTID VARCHAR(36) NOT NULL,
	  DESCRIPTION  VARCHAR(64)
);